#local run
#server.port=8083
#spring.data.mongodb.uri=mongodb://localhost:27017/recorddb
#spring.application.name=record-service


# Docker run
spring.application.name=record-service
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/recorddb}
server.port=${SERVER_PORT:8083}
